POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "cadama",
    "name": "Captain Adama",
    "password": "salainenindeed"
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "cadama",
    "name": "Captain Adama",
    "password": "salainen"
}

###
POST http://localhost:3003/api/login
content-type: application/json

{
    "username": "cadama",
    "password": "salainen"
}

###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer <GET TOTKEN BY LOGGING IN>

{
    "title": "Find the promise land2",
    "author": "Holy Landis",
    "url": "https://example.com/blog/promise-land2",
    "likes": 0
}