POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "cadama",
    "name": "Captain Adama",
    "password": "salainenindeed"
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "cadama",
    "name": "Captain Adama",
    "password": "salainen"
}

###
POST http://localhost:3003/api/login
content-type: application/json

{
    "username": "cadama",
    "password": "salainen"
}

###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer <GET TOTKEN BY LOGGING IN>
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNhZGFtYSIsImlkIjoiNjkzZGQxZDg5NDUyMmIxOGY2YTM5ZDJjIiwiaWF0IjoxNzY2MTYwNTcxfQ.GHyFmsRcvXGDc38Xuej2cvDuEfDCL01tRD31KWDOmJE

{
    "title": "Find the promise land3",
    "author": "Holy Landis",
    "url": "https://example.com/blog/promise-land3",
    "likes": 0
}